#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dubravica;
    
    #line 1 "..\..\Views\Report\_Form.cshtml"
    using Dubravica.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/_Form.cshtml")]
    public partial class _Views_Report__Form_cshtml : System.Web.Mvc.WebViewPage<ReportModel>
    {
        public _Views_Report__Form_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<script>

    var windowHeight;

    function windowWidth() {
        return $(window).width();
    }

    function windowHeight() {
        //return window.innerHeight;
        return $(window).height() - 130;
    }

    // add Event onResize and define method
    if (window.attachEvent) {
        window.attachEvent('onresize', function () {
            alert('attachEvent - resize');
        });
    }
    else if (window.addEventListener) {
        window.addEventListener('resize', function () {
            var id;
            $(window).resize(function () {
                clearTimeout(id);
                id = setTimeout(RecalcCount(25), 500);
            });
        }, true);
    }
    else {
        //The browser does not support Javascript event binding
    }

    // disable or enable input
    function InputEnable(el_s,el_d) {
        if ($(el_s).prop('checked') == true) {
            $(el_d).prop(""disabled"", false);
        }
        else {
            console.log('false');
            $(el_d).prop(""disabled"", true);
            $(el_d).prop(""value"", 0);
        }
    }

    function InitReportFilter() {
        InputEnable();
    }

    function RecalcCount(rowHeight) {
        var count;
        count = Math.round((windowHeight() - $('.navbar').height() - $('#top_menu').height() - $('.message').height() - $('footer').height()-25) / rowHeight);
        return count;
    }

</script>

<div");

WriteLiteral(" onload=\"InitReportFilter()\"");

WriteLiteral(">\r\n    <!-- pozdeji onclick tlacitka v menu -->\r\n    <section");

WriteLiteral(" id=\"reportForm\"");

WriteLiteral(">\r\n");

            
            #line 63 "..\..\Views\Report\_Form.cshtml"
        
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Report\_Form.cshtml"
         using (Html.BeginForm("Index", "Report", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n");

WriteLiteral("                ");

            
            #line 66 "..\..\Views\Report\_Form.cshtml"
           Write(Html.HiddenFor(model => model.StartId, new { @id = "start_id", @value = 0 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 67 "..\..\Views\Report\_Form.cshtml"
           Write(Html.HiddenFor(model => model.Count, new { @id = "count", @value = 60 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                <!-- time from -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 71 "..\..\Views\Report\_Form.cshtml"
               Write(Html.LabelFor(model => model.DateTimeFormFrom));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 72 "..\..\Views\Report\_Form.cshtml"
               Write(Html.TextBoxFor(model => model.DateTimeFrom, new { @id = "date-time_from", @class = "date-time", @type = "datetime-local", @name = "date-time_from", value = "2017-01-01T11:42:13.510" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!-- time to -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 76 "..\..\Views\Report\_Form.cshtml"
               Write(Html.LabelFor(model => model.DateTimeFormTo));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 77 "..\..\Views\Report\_Form.cshtml"
               Write(Html.TextBoxFor(model => model.DateTimeTo, new { @id = "date-time_to", @class = "date-time", @type = "datetime-local", @name = "date-time_to" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!-- rcp -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 81 "..\..\Views\Report\_Form.cshtml"
               Write(Html.LabelFor(model => model.Recipe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 82 "..\..\Views\Report\_Form.cshtml"
               Write(Html.TextBoxFor(model => model.Recipe, new { @id = "recipe", @class = "rcp-in", @type = "number", @name = "recipe", @value = "0", @min = 0, @max = 30, @style = "width:50px;" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!-- over Rcp limits -->\r\n             " +
"   <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 87 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.CheckBoxFor(model => model.Par0Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.LabelFor(model => model.Par0Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <!-- amount" +
" -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 94 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.CheckBoxFor(model => model.Par1Sel, new { @onchange = "InputEnable(this, tol1)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 95 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.LabelFor(model => model.Par1Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<label");

WriteLiteral(" for=\"tol1\"");

WriteLiteral(">&plusmn</label>\r\n");

WriteLiteral("                        ");

            
            #line 99 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.TextBoxFor(model => model.Par1Tol, new { @id = "tol1", @class = "tol-set", @name = "tol1", @value = "0", @type = "number", @min = 0, @max = 10, @step = "0.1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span>kg</span>\r\n                    </div>\r\n\r\n        " +
"        </div>\r\n                <!-- temperature -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 107 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.CheckBoxFor(model => model.Par2Sel, new { @onchange = "InputEnable(this, tol2)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 108 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.LabelFor(model => model.Par2Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<label");

WriteLiteral(" for=\"tol2\"");

WriteLiteral(">&plusmn</label>\r\n");

WriteLiteral("                        ");

            
            #line 112 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.TextBoxFor(model => model.Par2Tol, new { @id = "tol2", @class = "tol-set", @name = "tol2", @value = "0", @type = "number", @min = 0, @max = 10, @step = "0.1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span>°C</span>\r\n                    </div>\r\n          " +
"      </div>\r\n                <!-- step time -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 119 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.CheckBoxFor(model => model.Par3Sel, new { @onchange = "InputEnable(this, tol3)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 120 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.LabelFor(model => model.Par3Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<label");

WriteLiteral(" for=\"tol3\"");

WriteLiteral(">&plusmn</label>\r\n");

WriteLiteral("                        ");

            
            #line 124 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.TextBoxFor(model => model.Par3Tol, new { @id = "tol3", @class = "tol-set", @name = "tol3", @value = "0", @type = "number", @min = 0, @max = 10, @step = "0.1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span>min</span>\r\n                    </div>\r\n         " +
"       </div>\r\n                <!-- interstep time -->\r\n                <div");

WriteLiteral(" class=\"form-item\"");

WriteLiteral(">\r\n                    <div>\r\n");

WriteLiteral("                        ");

            
            #line 131 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.CheckBoxFor(model => model.Par4Sel, new { @onchange = "InputEnable(this, tol4)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 132 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.LabelFor(model => model.Par4Sel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<label");

WriteLiteral(" for=\"tol4\"");

WriteLiteral(">&plusmn</label>\r\n");

WriteLiteral("                        ");

            
            #line 136 "..\..\Views\Report\_Form.cshtml"
                   Write(Html.TextBoxFor(model => model.Par4Tol, new { @id = "tol4", @class = "tol-set", @name = "tol4", @value = "0", @type = "number", @min = 0, @max = 10, @step = "0.1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span>min</span>\r\n                    </div>\r\n         " +
"       </div>\r\n            </div>\r\n");

WriteLiteral("            <input");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"display: block; float: right; margin-left: 15px; padding: 2px 2px 2px 2px" +
";\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n");

            
            #line 142 "..\..\Views\Report\_Form.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </section>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
