#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dubravica;
    
    #line 1 "..\..\Views\Report\_Overview.cshtml"
    using Dubravica.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/_Overview.cshtml")]
    public partial class _Views_Report__Overview_cshtml : System.Web.Mvc.WebViewPage<ReportModel>
    {
        public _Views_Report__Overview_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<script>
    function getBatch(id) {
        //var batchId = document.getElementById(""batchid"").textContent;
        //var recipeno = document.getElementById(""recipeno"").textContent;
        window.location = ""/Report/getBatch?batchid="" + id; //+ ""&recipeno="" + recipeno;
    }
</script>
");

WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-condensed table-bordered table-hover table-responsive\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Report\_Overview.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Report\_Overview.cshtml"
      if (Model.Batches != null)
        {
            if (Model.Batches.Count > 0)
            {
                string statusClass = "";
                string runningStyle = "";

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteLiteral(" style=\"background-color:silver;\"");

WriteLiteral(@">
                    <th>Batch No.</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Product</th>
                    <th>Recipe</th>
                    <th>Batch status</th>
                    <th>Differences</th>
                </tr>
");

            
            #line 27 "..\..\Views\Report\_Overview.cshtml"

                int i = 0;
                foreach (Batch batch in Model.Batches)
                {
                    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Report\_Overview.cshtml"
                                      
                    if (batch.EndTime.Year < 2016 && !batch.batchStatus.HasFlag(StepStatus.Cancelled) &&
                        !batch.batchStatus.HasFlag(StepStatus.OK) && !batch.batchStatus.HasFlag(StepStatus.Error))
                    {
                       runningStyle = "background-color: lightgreen;";
                    }
                        

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1548), Tuple.Create("\"", 1577)
, Tuple.Create(Tuple.Create("", 1558), Tuple.Create("getBatch(", 1558), true)
            
            #line 38 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 1567), Tuple.Create<System.Object, System.Int32>(batch.Id
            
            #line default
            #line hidden
, 1567), false)
, Tuple.Create(Tuple.Create("", 1576), Tuple.Create(")", 1576), true)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1578), Tuple.Create("\"", 1615)
, Tuple.Create(Tuple.Create("", 1586), Tuple.Create("cursor:", 1586), true)
, Tuple.Create(Tuple.Create(" ", 1593), Tuple.Create("pointer;", 1594), true)
            
            #line 38 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 1602), Tuple.Create<System.Object, System.Int32>(runningStyle
            
            #line default
            #line hidden
, 1602), false)
);

WriteLiteral(">\r\n");

            
            #line 39 "..\..\Views\Report\_Overview.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Report\_Overview.cshtml"
                          runningStyle = "";
            
            #line default
            #line hidden
WriteLiteral("\r\n                        <td");

WriteLiteral(" id=\"BatchNo\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Report\_Overview.cshtml"
                                    Write(batch.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteAttribute("id", Tuple.Create(" id=\"", 1750), Tuple.Create("\"", 1765)
, Tuple.Create(Tuple.Create("", 1755), Tuple.Create("startDT_", 1755), true)
            
            #line 41 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 1763), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 1763), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Views\Report\_Overview.cshtml"
                                       Write(batch.StartTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 42 "..\..\Views\Report\_Overview.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.EndTime.Year < 2016)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td>No end</td>\r\n");

            
            #line 45 "..\..\Views\Report\_Overview.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <td");

WriteAttribute("id", Tuple.Create(" id=\"", 2034), Tuple.Create("\"", 2047)
, Tuple.Create(Tuple.Create("", 2039), Tuple.Create("endDT_", 2039), true)
            
            #line 48 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 2045), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 2045), false)
);

WriteLiteral(">");

            
            #line 48 "..\..\Views\Report\_Overview.cshtml"
                                         Write(batch.EndTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 49 "..\..\Views\Report\_Overview.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <td>");

            
            #line 50 "..\..\Views\Report\_Overview.cshtml"
                       Write(batch.RecipeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" id=\"recipeno\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\Report\_Overview.cshtml"
                                     Write(batch.RecipeNo);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 52 "..\..\Views\Report\_Overview.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.batchStatus.HasFlag(StepStatus.OK))
                        {
                            statusClass = "status-ok";
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 56 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.batchStatus.HasFlag(StepStatus.Skipped) || batch.batchStatus.HasFlag(StepStatus.ForcedStart))
                        {
                            statusClass = "status-skipped";
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 60 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.batchStatus.HasFlag(StepStatus.Error) || batch.batchStatus.HasFlag(StepStatus.Cancelled))
                        {
                            statusClass = "status-nok";
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 64 "..\..\Views\Report\_Overview.cshtml"
                           string title = ""; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 65 "..\..\Views\Report\_Overview.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.maxDiffAM != 0 || batch.minDiffAM != 0) { title += "Amount diff-" + "MAX: " + Math.Round((double)batch.maxDiffAM / 1000, 3) + "kg MIN: " + Math.Round((double)batch.minDiffAM / 1000, 3) + "kg \n"; }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 66 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.maxDiffTemp != 0 || batch.minDiffTemp != 0) { title += "Temperature diff-" + "MAX: " + Math.Round((double)batch.maxDiffTemp / 10, 1) + "°C MIN: " + Math.Round((double)batch.minDiffTemp / 10, 2) + "°C \n"; }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 67 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.maxDiffST != 0 || batch.minDiffST != 0) { title += "steptime diff- MAX: " + Math.Round((double)batch.maxDiffST / 60, 2) + "min MIN: " + Math.Round((double)batch.minDiffST / 60, 2) + "min \n"; }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 68 "..\..\Views\Report\_Overview.cshtml"
                         if (batch.maxDiffIST != 0 || batch.minDiffIST != 0) { title += "Inter step time diff- MAX: " + Math.Round((double)batch.maxDiffIST / 60, 2) + "min MIN: " + Math.Round((double)batch.minDiffIST / 60, 2) + "min \n"; }

            
            #line default
            #line hidden
WriteLiteral("                        <td");

WriteAttribute("class", Tuple.Create(" class=\"", 3901), Tuple.Create("\"", 3921)
            
            #line 69 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 3909), Tuple.Create<System.Object, System.Int32>(statusClass
            
            #line default
            #line hidden
, 3909), false)
);

WriteLiteral(">");

            
            #line 69 "..\..\Views\Report\_Overview.cshtml"
                                            Write(batch.batchStatus);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"top\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4018), Tuple.Create("\"", 4032)
            
            #line 70 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 4026), Tuple.Create<System.Object, System.Int32>(title
            
            #line default
            #line hidden
, 4026), false)
);

WriteLiteral("><span>");

            
            #line 70 "..\..\Views\Report\_Overview.cshtml"
                                                                                       Write(batch.diffStatus);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                    </tr>\r\n");

            
            #line 72 "..\..\Views\Report\_Overview.cshtml"
                    i++;
                }
            }
        }
    
            
            #line default
            #line hidden
WriteLiteral(@"
</table>
<script>
    function DateTime(date) {
        var offset = date.getTimezoneOffset();
        //console.log(offset);
        var offseted_miliseconds = date.getTime() - (offset * 60000);
        var DateTime = new Date(offseted_miliseconds);
        var localDateTime = DateTime.toLocaleString();
        return localDateTime;
    }
</script>
");

            
            #line 88 "..\..\Views\Report\_Overview.cshtml"
 for(int i=0; i < Model.Batches.Count;i++) { 

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n            var year = ");

            
            #line 90 "..\..\Views\Report\_Overview.cshtml"
                  Write(Model.Batches[i].StartTime.Year);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var month = ");

            
            #line 91 "..\..\Views\Report\_Overview.cshtml"
                   Write(Model.Batches[i].StartTime.Month);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var day = ");

            
            #line 92 "..\..\Views\Report\_Overview.cshtml"
                 Write(Model.Batches[i].StartTime.Day);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var hour = ");

            
            #line 93 "..\..\Views\Report\_Overview.cshtml"
                  Write(Model.Batches[i].StartTime.Hour);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var minute = ");

            
            #line 94 "..\..\Views\Report\_Overview.cshtml"
                    Write(Model.Batches[i].StartTime.Minute);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var second = ");

            
            #line 95 "..\..\Views\Report\_Overview.cshtml"
                    Write(Model.Batches[i].StartTime.Second);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var date = new Date(year, month - 1, day, hour, minute, second, 0)" +
";\r\n            var localDateTime = DateTime(date);\r\n            document.getElem" +
"entById(\"startDT_\" + \"");

            
            #line 98 "..\..\Views\Report\_Overview.cshtml"
                                             Write(i);

            
            #line default
            #line hidden
WriteLiteral("\").innerHTML = localDateTime;\r\n    </script>\r\n");

            
            #line 100 "..\..\Views\Report\_Overview.cshtml"

    if (Model.Batches[i].EndTime.Year < 2016) {

            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n            var yearExp = ");

            
            #line 103 "..\..\Views\Report\_Overview.cshtml"
                     Write(Model.Batches[i].EndTime.Year);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var monthExp = ");

            
            #line 104 "..\..\Views\Report\_Overview.cshtml"
                      Write(Model.Batches[i].EndTime.Month);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var dayExp = ");

            
            #line 105 "..\..\Views\Report\_Overview.cshtml"
                    Write(Model.Batches[i].EndTime.Day);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var hourExp = ");

            
            #line 106 "..\..\Views\Report\_Overview.cshtml"
                     Write(Model.Batches[i].EndTime.Hour);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var minuteExp = ");

            
            #line 107 "..\..\Views\Report\_Overview.cshtml"
                       Write(Model.Batches[i].EndTime.Minute);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var secondExp = ");

            
            #line 108 "..\..\Views\Report\_Overview.cshtml"
                       Write(Model.Batches[i].EndTime.Second);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            var expDate = new Date(yearExp, monthExp - 1, dayExp, hourExp, min" +
"uteExp, secondExp, 0);\r\n\r\n            var localExpDateTime = DateTime(expDate);\r" +
"\n            document.getElementById(\"endDT_\" + \"");

            
            #line 112 "..\..\Views\Report\_Overview.cshtml"
                                           Write(i);

            
            #line default
            #line hidden
WriteLiteral("\").innerHTML = localExpDateTime;\r\n        </script>\r\n");

            
            #line 114 "..\..\Views\Report\_Overview.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
