#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dubravica;
    
    #line 1 "..\..\Views\Report\_Overview.cshtml"
    using Dubravica.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/_Overview.cshtml")]
    public partial class _Views_Report__Overview_cshtml : System.Web.Mvc.WebViewPage<ReportModel>
    {
        public _Views_Report__Overview_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<script>
    function getBatch(id) {
        //var batchId = document.getElementById(""batchid"").textContent;
        console.log(id);
        //var recipeno = document.getElementById(""recipeno"").textContent;
        window.location = ""/Report/getBatch?batchid="" + id; //+ ""&recipeno="" + recipeno;
    }
</script>
");

WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-condensed table-bordered table-hover table-responsive\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Report\_Overview.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Report\_Overview.cshtml"
      if (Model.Batches != null)
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <tr>
                <!--<th style=""width: 65px"">Batch No.</th>
                <th style=""width: 155px"">Start</th>
                <th style=""width: 155px"">End</th>
                <th>Product</th>
                <th style=""width: 55px;"">Recipe</th>
                <th style=""width: 150px"">Differences</th> -->
                <th>Batch No.</th>
                <th>Start</th>
                <th>End</th>
                <th>Product</th>
                <th>Recipe</th>
                <th>Differences</th>
            </tr>
");

            
            #line 29 "..\..\Views\Report\_Overview.cshtml"
            foreach (Batch batch in Model.Batches)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1191), Tuple.Create("\"", 1220)
, Tuple.Create(Tuple.Create("", 1201), Tuple.Create("getBatch(", 1201), true)
            
            #line 31 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 1210), Tuple.Create<System.Object, System.Int32>(batch.Id
            
            #line default
            #line hidden
, 1210), false)
, Tuple.Create(Tuple.Create("", 1219), Tuple.Create(")", 1219), true)
);

WriteLiteral(">\r\n                    <td");

WriteLiteral(" id=\"\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\Report\_Overview.cshtml"
                         Write(batch.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 33 "..\..\Views\Report\_Overview.cshtml"
                   Write(batch.StartTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 34 "..\..\Views\Report\_Overview.cshtml"
                   Write(batch.EndTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 35 "..\..\Views\Report\_Overview.cshtml"
                   Write(batch.RecipeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td");

WriteLiteral(" id=\"recipeno\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Report\_Overview.cshtml"
                                 Write(batch.RecipeNo);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 37 "..\..\Views\Report\_Overview.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Report\_Overview.cshtml"
                       string title = ""; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 38 "..\..\Views\Report\_Overview.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Report\_Overview.cshtml"
                     if (batch.maxDiffAM != 0 || batch.minDiffAM != 0) { title += "Amount diff-" + "MAX: " + Math.Round((double)batch.maxDiffAM / 1000, 3) + "kg MIN: " + Math.Round((double)batch.minDiffAM / 1000, 3) + "kg \n"; }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 39 "..\..\Views\Report\_Overview.cshtml"
                     if (batch.maxDiffTemp != 0 || batch.minDiffTemp != 0) { title += "Temperature diff-" + "MAX: " + Math.Round((double)batch.maxDiffTemp / 10, 1) + "°C MIN: " + Math.Round((double)batch.minDiffTemp / 10, 2) + "°C \n"; }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 40 "..\..\Views\Report\_Overview.cshtml"
                     if (batch.maxDiffST != 0 || batch.minDiffST != 0) { title += "steptime diff- MAX: " + Math.Round((double)batch.maxDiffST / 60, 2) + "min MIN: " + Math.Round((double)batch.minDiffST / 60, 2) + "min \n"; }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Report\_Overview.cshtml"
                     if (batch.maxDiffIST != 0 || batch.minDiffIST != 0) { title += "Inter step time diff- MAX: " + Math.Round((double)batch.maxDiffIST / 60, 2) + "min MIN: " + Math.Round((double)batch.minDiffIST / 60, 2) + "min \n"; }

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"color: #ff0000;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2494), Tuple.Create("\"", 2508)
            
            #line 42 "..\..\Views\Report\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 2502), Tuple.Create<System.Object, System.Int32>(title
            
            #line default
            #line hidden
, 2502), false)
);

WriteLiteral("><span><b>");

            
            #line 42 "..\..\Views\Report\_Overview.cshtml"
                                                                   Write(batch.status);

            
            #line default
            #line hidden
WriteLiteral("</b></span></td>\r\n                </tr>\r\n");

            
            #line 44 "..\..\Views\Report\_Overview.cshtml"
            }
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n</table>\r\n");

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
