#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 2 "..\..\Views\Home\Homepage.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Dubravica;
    
    #line 1 "..\..\Views\Home\Homepage.cshtml"
    using Dubravica.Controllers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Homepage.cshtml")]
    public partial class _Views_Home_Homepage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Homepage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h2>Welcome to Diosna cloud</h2>\r\n");

            
            #line 6 "..\..\Views\Home\Homepage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Home\Homepage.cshtml"
     for (int i = 0; i < ViewBag.Count; i++)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 181), Tuple.Create("\"", 216)
, Tuple.Create(Tuple.Create("", 188), Tuple.Create("/Menu?id=", 188), true)
            
            #line 8 "..\..\Views\Home\Homepage.cshtml"
, Tuple.Create(Tuple.Create("", 197), Tuple.Create<System.Object, System.Int32>(ViewBag.Numbers[i]
            
            #line default
            #line hidden
, 197), false)
);

WriteLiteral(" class=\"btn-primary btn-lg\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Home\Homepage.cshtml"
                                                                     Write(ViewBag.Text[i]);

            
            #line default
            #line hidden
WriteLiteral("&rAarr;</a>\r\n");

            
            #line 9 "..\..\Views\Home\Homepage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
